# Generated by Django 2.2.5 on 2021-09-07 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(default='nobody', max_length=200)),
                ('words_text', models.CharField(max_length=200)),
                ('data_text', models.CharField(max_length=200)),
                ('editkey', models.CharField(default='dummy', max_length=200)),
                ('begin_date', models.DateTimeField(verbose_name='commencement date')),
                ('end_date', models.DateTimeField(verbose_name='expiration date')),
            ],
            options={
                'ordering': ['end_date'],
            },
        ),
    ]
