# Generated by Django 2.2.5 on 2021-09-07 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='length',
            field=models.IntegerField(choices=[(0, 'none'), (1, 'day'), (2, 'week'), (3, 'month')], default=0),
        ),
    ]
