# Generated by Django 2.2.5 on 2021-09-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordb', '0002_item_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='data_text',
            field=models.CharField(max_length=1000),
        ),
    ]
