# Generated by Django 2.2.5 on 2021-09-07 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordb', '0003_auto_20210907_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
